### ISSUE TITLE
[✅] URI 파싱

### ISSUE THREAD

**Issue by codeyoma** [42-webserv/SpaceX#18]
**내용**
* cgi를 위한 url 파싱이 필요한 건가! -> 필요한 듯

`localhost:80/script.php?name=John`

[origin-form](https://www.rfc-editor.org/rfc/rfc9112#name-origin-form)      -> 자동으로
* The most common form of request-target is the "origin-form".

`  origin-form    = absolute-path [ "?" query ] `
`http://www.example.org/where?q=now`
```
GET /where?q=now HTTP/1.1
Host: www.example.org
```
---

[absolute-form](https://www.rfc-editor.org/rfc/rfc9112#name-absolute-form)      -> 프록시 일때만
* When making a request to a proxy, other than a CONNECT or server-wide OPTIONS request (as detailed below), a client MUST send the target URI in "absolute-form" as the request-target.

` absolute-form  = absolute-URI `
` GET http://www.example.org/pub/WWW/TheProject.html HTTP/1.1 `

---

[authority-form](https://www.rfc-editor.org/rfc/rfc9112#name-authority-form) -> CONNECT 요청에만
[asterisk-form](https://www.rfc-editor.org/rfc/rfc9112#name-asterisk-form) -> OPTIONS 요청에만

</br></br>

## TASK

- [x] '?' - query : 보류
- [x] '#' - fragment :  보류

 
## PATH
- [x] syntax_request에서 uri 검사 추가
- [x] '%20' - SP (%HexHex) -> path resolver로
- [x] //// - 연속일때 하나로 -> path resolver로
- [x] Define a directory or a file from where the file should be searched (for example, if url /kapouet is rooted to /tmp/www, url /kapouet/pouic/toto/pouet is /tmp/www/pouic/toto/pouet).

**Comment by codeyoma** [comment]
For example, the following three URIs are equivalent:

   http://example.com:80/~smith/home.html
   http://EXAMPLE.com/%7Esmith/home.html
   http://EXAMPLE.com:/%7esmith/home.html

[rfc 9110 에서](https://www.rfc-editor.org/rfc/rfc9110#section-4.2.3-6)
