### ISSUE TITLE
[⚙] TODO : uri, config

### ISSUE THREAD

**Issue by codeyoma** [42-webserv/SpaceX#27]
**내용**
* uri 관련 사항
</br></br>

**태스크**

- [x] get_uri_location_ 예외케이스 추가
- [x] (/로 끝날때) index 있을 경우 붙여서
- [x] uri 합칠때 사이사이 '/' 넣어주기
- [x] Cgi path info는 실행 프로그램 위치로 수정. 예: 파이썬, 펄 위치
- [x] options 지우기
- [x] method에 all 추가
- [x] get_uri_location_ 리턴값 uri_location_t const&로 반환
