### ISSUE TITLE
[✅] Subject CheckList

### ISSUE THREAD

**Issue by enaenen** [42-webserv/SpaceX#73]
**Madatory Checklist**
* 여기다가 내용 쓰세용

</br></br>

**태스크**

### Makefile
- [x] CFLAGS check (-Wall -Wextra -Werror)
- [x] C 함수사용 여부 (C++로 변환 가능여부)
- [x] not using boost library

### Requirements of Madatory

- [x] ./webserv [configuration file]
- [x] kqueue - non-blocking
- [x] using default path
- [x] read or write - only using KQUEUE EVENT
- [x] not using errno
- [x] #76
- [x] You server must have default error pages if none are provided.
- [x] • You must be able to serve a fully static website.
- [x] • Clients must be able to upload files.
- [x] GET
- [x] POST
- [x] DELETE
- [x] Your server must be able to listen to multiple ports (see Configuration file)

### test
- [x] 42Tester
- [x] siege  

> - [x] siege -b http://localhost
> - [x] siege with two computers on same time

- [x] siege -b http://localhost:8080 & 42tester동시에  테스트 해보기
- [x] File upload

- [x] Autoindex (directory listing)
- [ ]

### bounus

- [x] handle multiple CGI
-> 다양한 확장자 or 여러 기능을 호출 가능한 (upload.py, env_print.py, image_generator.py)
>  [ ] upload.py
>  [ ] sum.pl

- [x] cookies and session management
